/**
 * BAD DECISION — Cascading Location Data
 * Comprehensive continent → country → state/region mapping
 */

export interface LocationOption {
  value: string;
  label: string;
}

export interface CountryData {
  value: string;
  label: string;
  states: LocationOption[];
}

export interface ContinentData {
  value: string;
  label: string;
  emoji: string;
  countries: CountryData[];
}

export const locationData: ContinentData[] = [
  {
    value: "africa",
    label: "Africa",
    emoji: "🌍",
    countries: [
      {
        value: "nigeria",
        label: "Nigeria",
        states: [
          { value: "abia", label: "Abia" },
          { value: "adamawa", label: "Adamawa" },
          { value: "akwa_ibom", label: "Akwa Ibom" },
          { value: "anambra", label: "Anambra" },
          { value: "bauchi", label: "Bauchi" },
          { value: "bayelsa", label: "Bayelsa" },
          { value: "benue", label: "Benue" },
          { value: "borno", label: "Borno" },
          { value: "cross_river", label: "Cross River" },
          { value: "delta", label: "Delta" },
          { value: "ebonyi", label: "Ebonyi" },
          { value: "edo", label: "Edo" },
          { value: "ekiti", label: "Ekiti" },
          { value: "enugu", label: "Enugu" },
          { value: "fct", label: "FCT (Abuja)" },
          { value: "gombe", label: "Gombe" },
          { value: "imo", label: "Imo" },
          { value: "jigawa", label: "Jigawa" },
          { value: "kaduna", label: "Kaduna" },
          { value: "kano", label: "Kano" },
          { value: "katsina", label: "Katsina" },
          { value: "kebbi", label: "Kebbi" },
          { value: "kogi", label: "Kogi" },
          { value: "kwara", label: "Kwara" },
          { value: "lagos", label: "Lagos" },
          { value: "nasarawa", label: "Nasarawa" },
          { value: "niger", label: "Niger" },
          { value: "ogun", label: "Ogun" },
          { value: "ondo", label: "Ondo" },
          { value: "osun", label: "Osun" },
          { value: "oyo", label: "Oyo" },
          { value: "plateau", label: "Plateau" },
          { value: "rivers", label: "Rivers" },
          { value: "sokoto", label: "Sokoto" },
          { value: "taraba", label: "Taraba" },
          { value: "yobe", label: "Yobe" },
          { value: "zamfara", label: "Zamfara" },
        ],
      },
      {
        value: "south_africa",
        label: "South Africa",
        states: [
          { value: "eastern_cape", label: "Eastern Cape" },
          { value: "free_state", label: "Free State" },
          { value: "gauteng", label: "Gauteng" },
          { value: "kwazulu_natal", label: "KwaZulu-Natal" },
          { value: "limpopo", label: "Limpopo" },
          { value: "mpumalanga", label: "Mpumalanga" },
          { value: "north_west", label: "North West" },
          { value: "northern_cape", label: "Northern Cape" },
          { value: "western_cape", label: "Western Cape" },
        ],
      },
      {
        value: "kenya",
        label: "Kenya",
        states: [
          { value: "nairobi", label: "Nairobi" },
          { value: "mombasa", label: "Mombasa" },
          { value: "kisumu", label: "Kisumu" },
          { value: "nakuru", label: "Nakuru" },
          { value: "eldoret", label: "Eldoret" },
          { value: "kiambu", label: "Kiambu" },
          { value: "machakos", label: "Machakos" },
          { value: "nyeri", label: "Nyeri" },
          { value: "meru", label: "Meru" },
          { value: "garissa", label: "Garissa" },
          { value: "kakamega", label: "Kakamega" },
          { value: "bungoma", label: "Bungoma" },
          { value: "malindi", label: "Malindi" },
          { value: "kitale", label: "Kitale" },
          { value: "thika", label: "Thika" },
        ],
      },
      {
        value: "egypt",
        label: "Egypt",
        states: [
          { value: "cairo", label: "Cairo" },
          { value: "alexandria", label: "Alexandria" },
          { value: "giza", label: "Giza" },
          { value: "shubra_el_kheima", label: "Shubra El Kheima" },
          { value: "portsaid", label: "Port Said" },
          { value: "suez", label: "Suez" },
          { value: "luxor", label: "Luxor" },
          { value: "aswan", label: "Aswan" },
          { value: "tanta", label: "Tanta" },
          { value: "mansoura", label: "Mansoura" },
        ],
      },
      {
        value: "ghana",
        label: "Ghana",
        states: [
          { value: "greater_accra", label: "Greater Accra" },
          { value: "ashanti", label: "Ashanti" },
          { value: "western", label: "Western" },
          { value: "eastern", label: "Eastern" },
          { value: "central", label: "Central" },
          { value: "volta", label: "Volta" },
          { value: "northern", label: "Northern" },
          { value: "upper_east", label: "Upper East" },
          { value: "upper_west", label: "Upper West" },
          { value: "brong_ahafo", label: "Brong-Ahafo" },
        ],
      },
      {
        value: "ethiopia",
        label: "Ethiopia",
        states: [
          { value: "addis_ababa", label: "Addis Ababa" },
          { value: "oromia", label: "Oromia" },
          { value: "amhara", label: "Amhara" },
          { value: "tigray", label: "Tigray" },
          { value: "snnpr", label: "SNNPR" },
          { value: "dire_dawa", label: "Dire Dawa" },
        ],
      },
      {
        value: "tanzania",
        label: "Tanzania",
        states: [
          { value: "dar_es_salaam", label: "Dar es Salaam" },
          { value: "dodoma", label: "Dodoma" },
          { value: "mwanza", label: "Mwanza" },
          { value: "arusha", label: "Arusha" },
          { value: "zanzibar", label: "Zanzibar" },
          { value: "mbeya", label: "Mbeya" },
        ],
      },
      {
        value: "morocco",
        label: "Morocco",
        states: [
          { value: "casablanca", label: "Casablanca" },
          { value: "rabat", label: "Rabat" },
          { value: "marrakech", label: "Marrakech" },
          { value: "fes", label: "Fès" },
          { value: "tangier", label: "Tangier" },
          { value: "agadir", label: "Agadir" },
        ],
      },
      {
        value: "rwanda",
        label: "Rwanda",
        states: [
          { value: "kigali", label: "Kigali" },
          { value: "eastern", label: "Eastern Province" },
          { value: "northern", label: "Northern Province" },
          { value: "southern", label: "Southern Province" },
          { value: "western", label: "Western Province" },
        ],
      },
      {
        value: "uganda",
        label: "Uganda",
        states: [
          { value: "kampala", label: "Kampala" },
          { value: "entebbe", label: "Entebbe" },
          { value: "jinja", label: "Jinja" },
          { value: "mbarara", label: "Mbarara" },
          { value: "gulu", label: "Gulu" },
        ],
      },
      {
        value: "cameroon",
        label: "Cameroon",
        states: [
          { value: "littoral", label: "Littoral" },
          { value: "centre", label: "Centre" },
          { value: "southwest", label: "South-West" },
          { value: "northwest", label: "North-West" },
          { value: "far_north", label: "Far North" },
        ],
      },
      {
        value: "algeria",
        label: "Algeria",
        states: [
          { value: "algiers", label: "Algiers" },
          { value: "oran", label: "Oran" },
          { value: "constantine", label: "Constantine" },
          { value: "annaba", label: "Annaba" },
          { value: "setif", label: "Sétif" },
          { value: "blida", label: "Blida" },
          { value: "tlemcen", label: "Tlemcen" },
          { value: "batna", label: "Batna" },
        ],
      },
      {
        value: "angola",
        label: "Angola",
        states: [
          { value: "luanda", label: "Luanda" },
          { value: "huambo", label: "Huambo" },
          { value: "benguela", label: "Benguela" },
          { value: "huila", label: "Huíla" },
          { value: "cabinda", label: "Cabinda" },
          { value: "namibe", label: "Namibe" },
          { value: " Cuando_Cubango", label: "Cuando Cubango" },
          { value: "malanje", label: "Malanje" },
        ],
      },
      {
        value: "benin",
        label: "Benin",
        states: [
          { value: "littoral_benin", label: "Littoral" },
          { value: "atlantique", label: "Atlantique" },
          { value: "oueme", label: "Ouémé" },
          { value: "zou", label: "Zou" },
          { value: "borgou", label: "Borgou" },
          { value: "mono", label: "Mono" },
          { value: "atakora", label: "Atakora" },
          { value: "donga", label: "Donga" },
        ],
      },
      {
        value: "botswana",
        label: "Botswana",
        states: [
          { value: "gaborone", label: "Gaborone" },
          { value: "francistown", label: "Francistown" },
          { value: "central_district", label: "Central District" },
          { value: "kweneng", label: "Kweneng" },
          { value: "kgatleng", label: "Kgatleng" },
          { value: "north_west_botswana", label: "North West" },
          { value: "southern_district", label: "Southern District" },
        ],
      },
      {
        value: "burkina_faso",
        label: "Burkina Faso",
        states: [
          { value: "centre_burkina", label: "Centre" },
          { value: "cascade", label: "Cascade" },
          { value: "hauts_bassins", label: "Hauts-Bassins" },
          { value: "centre_ouest", label: "Centre-Ouest" },
          { value: "centre_nord", label: "Centre-Nord" },
          { value: "sahel", label: "Sahel" },
          { value: "est_burkina", label: "Est" },
          { value: "boucle_du_mouhoun", label: "Boucle du Mouhoun" },
        ],
      },
      {
        value: "burundi",
        label: "Burundi",
        states: [
          { value: "bujumbura", label: "Bujumbura" },
          { value: "gitega", label: "Gitega" },
          { value: "kirundo", label: "Kirundo" },
          { value: "nte", label: "Ngozi" },
          { value: "muramvya", label: "Muramvya" },
        ],
      },
      {
        value: "cabo_verde",
        label: "Cabo Verde",
        states: [
          { value: "santiago", label: "Santiago" },
          { value: "sao_vicente", label: "São Vicente" },
          { value: "santo_antao", label: "Santo Antão" },
          { value: "sal", label: "Sal" },
          { value: "boa_vista", label: "Boa Vista" },
          { value: "fogo", label: "Fogo" },
        ],
      },
      {
        value: "central_african_republic",
        label: "Central African Republic",
        states: [
          { value: "bangui", label: "Bangui" },
          { value: "bambari", label: "Bambari" },
          { value: "bouar", label: "Bouar" },
          { value: "bossangoa", label: "Bossangoa" },
          { value: "berberati", label: "Berberati" },
        ],
      },
      {
        value: "chad",
        label: "Chad",
        states: [
          { value: "ndjamena", label: "N'Djamena" },
          { value: "moundou", label: "Moundou" },
          { value: "sarh", label: "Sarh" },
          { value: "abeche", label: "Abéché" },
          { value: "kelo", label: "Kélo" },
          { value: "bongor", label: "Bongor" },
        ],
      },
      {
        value: "comoros",
        label: "Comoros",
        states: [
          { value: "grande_comore", label: "Grande Comore" },
          { value: "anjouan", label: "Anjouan" },
          { value: "moheli", label: "Mohéli" },
        ],
      },
      {
        value: "congo_brazzaville",
        label: "Congo (Brazzaville)",
        states: [
          { value: "brazzaville", label: "Brazzaville" },
          { value: "pointe_noire", label: "Pointe-Noire" },
          { value: "niari", label: "Niari" },
          { value: "likouala", label: "Likouala" },
          { value: "pool", label: "Pool" },
          { value: "sangha", label: "Sangha" },
        ],
      },
      {
        value: "congo_drc",
        label: "Congo (DRC)",
        states: [
          { value: "kinshasa", label: "Kinshasa" },
          { value: "lubumbashi", label: "Lubumbashi" },
          { value: "mbuji_mayi", label: "Mbuji-Mayi" },
          { value: "kananga", label: "Kananga" },
          { value: "kisangani", label: "Kisangani" },
          { value: "goma", label: "Goma" },
          { value: "bukavu", label: "Bukavu" },
          { value: "matadi", label: "Matadi" },
          { value: "likasi", label: "Likasi" },
          { value: "kalemie", label: "Kalemie" },
        ],
      },
      {
        value: "djibouti",
        label: "Djibouti",
        states: [
          { value: "djibouti_city", label: "Djibouti City" },
          { value: "ali_sabieh", label: "Ali Sabieh" },
          { value: "dikhil", label: "Dikhil" },
          { value: "tadjourah", label: "Tadjourah" },
          { value: "obock", label: "Obock" },
        ],
      },
      {
        value: "equatorial_guinea",
        label: "Equatorial Guinea",
        states: [
          { value: "malabo", label: "Malabo" },
          { value: "bata", label: "Bata" },
          { value: "ebibeyin", label: "Ebibeyin" },
          { value: "mongomo", label: "Mongomo" },
        ],
      },
      {
        value: "eritrea",
        label: "Eritrea",
        states: [
          { value: "asmara", label: "Asmara" },
          { value: "keren", label: "Keren" },
          { value: "massawa", label: "Massawa" },
          { value: "assab", label: "Assab" },
          { value: "mendefera", label: "Mendefera" },
        ],
      },
      {
        value: "eswatini",
        label: "Eswatini",
        states: [
          { value: "hohho", label: "Hhohho" },
          { value: "manzini", label: "Manzini" },
          { value: "shiselweni", label: "Shiselweni" },
          { value: "lubombo", label: "Lubombo" },
        ],
      },
      {
        value: "gabon",
        label: "Gabon",
        states: [
          { value: "libreville", label: "Libreville" },
          { value: "port_gentil", label: "Port-Gentil" },
          { value: "franceville", label: "Franceville" },
          { value: "oyo", label: "Oyem" },
          { value: "moanda", label: "Moanda" },
        ],
      },
      {
        value: "gambia",
        label: "Gambia",
        states: [
          { value: "banjul", label: "Banjul" },
          { value: "kanifing", label: "Kanifing" },
          { value: "brikama", label: "Brikama" },
          { value: "mansakonko", label: "Mansakonko" },
          { value: "kerewan", label: "Kerewan" },
          { value: "basse", label: "Basse" },
        ],
      },
      {
        value: "guinea",
        label: "Guinea",
        states: [
          { value: "conakry", label: "Conakry" },
          { value: "n_zerekore", label: "Nzérékoré" },
          { value: "kankan", label: "Kankan" },
          { value: "kindia", label: "Kindia" },
          { value: "labe", label: "Labé" },
          { value: "faranah", label: "Faranah" },
          { value: "mamou", label: "Mamou" },
          { value: "boke", label: "Boké" },
        ],
      },
      {
        value: "guinea_bissau",
        label: "Guinea-Bissau",
        states: [
          { value: "bissau", label: "Bissau" },
          { value: "bafata", label: "Bafatá" },
          { value: "gabu", label: "Gabú" },
          { value: "biombo", label: "Biombo" },
          { value: "cacheu", label: "Cacheu" },
        ],
      },
      {
        value: "ivory_coast",
        label: "Ivory Coast",
        states: [
          { value: "abidjan", label: "Abidjan" },
          { value: "yamoussoukro", label: "Yamoussoukro" },
          { value: "bouake", label: "Bouaké" },
          { value: "daloa", label: "Daloa" },
          { value: "san_pedro", label: "San-Pédro" },
          { value: "korhogo", label: "Korhogo" },
          { value: "man", label: "Man" },
          { value: "gagnoa", label: "Gagnoa" },
        ],
      },
      {
        value: "lesotho",
        label: "Lesotho",
        states: [
          { value: "maseru", label: "Maseru" },
          { value: "leribe", label: "Leribe" },
          { value: "mafeteng", label: "Mafeteng" },
          { value: "mokhotlong", label: "Mokhotlong" },
          { value: "qachas_nek", label: "Qacha's Nek" },
          { value: "berea", label: "Berea" },
        ],
      },
      {
        value: "liberia",
        label: "Liberia",
        states: [
          { value: "monrovia", label: "Monrovia" },
          { value: "bong", label: "Bong" },
          { value: "nimba", label: "Nimba" },
          { value: "lofa", label: "Lofa" },
          { value: "bomi", label: "Bomi" },
          { value: "grand_bassa", label: "Grand Bassa" },
          { value: "margibi", label: "Margibi" },
        ],
      },
      {
        value: "libya",
        label: "Libya",
        states: [
          { value: "tripoli", label: "Tripoli" },
          { value: "benghazi", label: "Benghazi" },
          { value: "misrata", label: "Misrata" },
          { value: "sabha", label: "Sabha" },
          { value: "bayda", label: "Bayda" },
          { value: "zawiya", label: "Zawiya" },
          { value: "zliten", label: "Zliten" },
        ],
      },
      {
        value: "madagascar",
        label: "Madagascar",
        states: [
          { value: "antananarivo", label: "Antananarivo" },
          { value: "toamasina", label: "Toamasina" },
          { value: "mahajanga", label: "Mahajanga" },
          { value: "fianarantsoa", label: "Fianarantsoa" },
          { value: "toliara", label: "Toliara" },
          { value: "antsiranana", label: "Antsiranana" },
          { value: "antsohihy", label: "Antsohihy" },
        ],
      },
      {
        value: "malawi",
        label: "Malawi",
        states: [
          { value: "lilongwe", label: "Lilongwe" },
          { value: "blantyre", label: "Blantyre" },
          { value: "mzuzu", label: "Mzuzu" },
          { value: "zomba", label: "Zomba" },
          { value: "kasungu", label: "Kasungu" },
          { value: "mangochi", label: "Mangochi" },
        ],
      },
      {
        value: "mali",
        label: "Mali",
        states: [
          { value: "bamako", label: "Bamako" },
          { value: "sikasso", label: "Sikasso" },
          { value: "kayes", label: "Kayes" },
          { value: "segou", label: "Ségou" },
          { value: "mopti", label: "Mopti" },
          { value: "gao", label: "Gao" },
          { value: "timbuktu", label: "Timbuktu" },
          { value: "kidal", label: "Kidal" },
        ],
      },
      {
        value: "mauritania",
        label: "Mauritania",
        states: [
          { value: "nouakchott", label: "Nouakchott" },
          { value: "nouadhibou", label: "Nouadhibou" },
          { value: "rosso", label: "Rosso" },
          { value: "kaedi", label: "Kaédi" },
          { value: "zouerate", label: "Zouérate" },
          { value: "nema", label: "Néma" },
        ],
      },
      {
        value: "mauritius",
        label: "Mauritius",
        states: [
          { value: "port_louis", label: "Port Louis" },
          { value: "curepipe", label: "Curepipe" },
          { value: "vacoas_phoenix", label: "Vacoas-Phoenix" },
          { value: "quatre_bornes", label: "Quatre Bornes" },
          { value: "rodrigues", label: "Rodrigues" },
        ],
      },
      {
        value: "mozambique",
        label: "Mozambique",
        states: [
          { value: "maputo", label: "Maputo" },
          { value: "beira", label: "Beira" },
          { value: "nampula", label: "Nampula" },
          { value: "chimoio", label: "Chimoio" },
          { value: "tete", label: "Tete" },
          { value: "quilimane", label: "Quelimane" },
          { value: "inhambane", label: "Inhambane" },
        ],
      },
      {
        value: "namibia",
        label: "Namibia",
        states: [
          { value: "windhoek", label: "Windhoek" },
          { value: "swakopmund", label: "Swakopmund" },
          { value: "walvis_bay", label: "Walvis Bay" },
          { value: "oshikoto", label: "Oshikoto" },
          { value: "ohangwena", label: "Ohangwena" },
          { value: "omusati", label: "Omusati" },
          { value: "kavango_east", label: "Kavango East" },
          { value: "kavango_west", label: "Kavango West" },
        ],
      },
      {
        value: "niger",
        label: "Niger",
        states: [
          { value: "niamey", label: "Niamey" },
          { value: "zinder", label: "Zinder" },
          { value: "maradi", label: "Maradi" },
          { value: "agadez", label: "Agadez" },
          { value: "tahoua", label: "Tahoua" },
          { value: "diffa", label: "Diffa" },
          { value: "dosso", label: "Dosso" },
        ],
      },
      {
        value: "sao_tome_and_principe",
        label: "São Tomé and Príncipe",
        states: [
          { value: "sao_tome", label: "São Tomé" },
          { value: "principe", label: "Príncipe" },
          { value: "agua_grande", label: "Água Grande" },
          { value: "me_zochi", label: "Mé-Zóchi" },
        ],
      },
      {
        value: "senegal",
        label: "Senegal",
        states: [
          { value: "dakar", label: "Dakar" },
          { value: "thies", label: "Thiès" },
          { value: "saint_louis", label: "Saint-Louis" },
          { value: "ziguinchor", label: "Ziguinchor" },
          { value: "kaolack", label: "Kaolack" },
          { value: "tambacounda", label: "Tambacounda" },
          { value: "diourbel", label: "Diourbel" },
          { value: "louga", label: "Louga" },
        ],
      },
      {
        value: "seychelles",
        label: "Seychelles",
        states: [
          { value: "victoria", label: "Victoria" },
          { value: "anse_boileau", label: "Anse Boileau" },
          { value: "beau_vallon", label: "Beau Vallon" },
          { value: "cascade_seychelles", label: "Cascade" },
          { value: "praslin", label: "Praslin" },
        ],
      },
      {
        value: "sierra_leone",
        label: "Sierra Leone",
        states: [
          { value: "freetown", label: "Freetown" },
          { value: "bo", label: "Bo" },
          { value: "kenema", label: "Kenema" },
          { value: "makeni", label: "Makeni" },
          { value: "koidu", label: "Koidu" },
          { value: "port_loko", label: "Port Loko" },
        ],
      },
      {
        value: "somalia",
        label: "Somalia",
        states: [
          { value: "mogadishu", label: "Mogadishu" },
          { value: "hargeysa", label: "Hargeysa" },
          { value: "kismaayo", label: "Kismaayo" },
          { value: "bosaaso", label: "Bosaaso" },
          { value: "garoowe", label: "Garoowe" },
          { value: "marka", label: "Marka" },
        ],
      },
      {
        value: "south_sudan",
        label: "South Sudan",
        states: [
          { value: "juba", label: "Juba" },
          { value: "wau", label: "Wau" },
          { value: "malakal", label: "Malakal" },
          { value: "rumbek", label: "Rumbek" },
          { value: "yambio", label: "Yambio" },
          { value: "bor", label: "Bor" },
          { value: "aweil", label: "Aweil" },
          { value: "torit", label: "Torit" },
        ],
      },
      {
        value: "sudan",
        label: "Sudan",
        states: [
          { value: "khartoum", label: "Khartoum" },
          { value: "omdurman", label: "Omdurman" },
          { value: "port_sudan", label: "Port Sudan" },
          { value: "kassala", label: "Kassala" },
          { value: "el_obeid", label: "El Obeid" },
          { value: "nyala", label: "Nyala" },
          { value: "gedaref", label: "Gedaref" },
        ],
      },
      {
        value: "togo",
        label: "Togo",
        states: [
          { value: "lome", label: "Lomé" },
          { value: "sokode", label: "Sokodé" },
          { value: "kara", label: "Kara" },
          { value: "atsieme", label: "Atakpamé" },
          { value: "dapaong", label: "Dapaong" },
          { value: "tsievie", label: "Tsévié" },
        ],
      },
      {
        value: "tunisia",
        label: "Tunisia",
        states: [
          { value: "tunis", label: "Tunis" },
          { value: "sfax", label: "Sfax" },
          { value: "sousse", label: "Sousse" },
          { value: "kairouan", label: "Kairouan" },
          { value: "bizerte", label: "Bizerte" },
          { value: "gabes", label: "Gabès" },
          { value: "ariana", label: "Ariana" },
          { value: "monastir", label: "Monastir" },
        ],
      },
      {
        value: "western_sahara",
        label: "Western Sahara",
        states: [
          { value: "laayoune", label: "Laâyoune" },
          { value: "dakhla", label: "Dakhla" },
          { value: "smara", label: "Smara" },
          { value: "boujdour", label: "Boujdour" },
        ],
      },
      {
        value: "zambia",
        label: "Zambia",
        states: [
          { value: "lusaka", label: "Lusaka" },
          { value: "kitwe", label: "Kitwe" },
          { value: "ndola", label: "Ndola" },
          { value: "kabwe", label: "Kabwe" },
          { value: "chingola", label: "Chingola" },
          { value: "livingstone", label: "Livingstone" },
          { value: "kasama", label: "Kasama" },
          { value: "chipata", label: "Chipata" },
        ],
      },
      {
        value: "zimbabwe",
        label: "Zimbabwe",
        states: [
          { value: "harare", label: "Harare" },
          { value: "bulawayo", label: "Bulawayo" },
          { value: "mutare", label: "Mutare" },
          { value: "gweru", label: "Gweru" },
          { value: "masvingo", label: "Masvingo" },
          { value: "kadoma", label: "Kadoma" },
          { value: "chitungwiza", label: "Chitungwiza" },
          { value: "hwange", label: "Hwange" },
        ],
      },
    ],
  },
  {
    value: "north_america",
    label: "North America",
    emoji: "🌎",
    countries: [
      {
        value: "usa",
        label: "United States",
        states: [
          { value: "alabama", label: "Alabama" },
          { value: "alaska", label: "Alaska" },
          { value: "arizona", label: "Arizona" },
          { value: "arkansas", label: "Arkansas" },
          { value: "california", label: "California" },
          { value: "colorado", label: "Colorado" },
          { value: "connecticut", label: "Connecticut" },
          { value: "delaware", label: "Delaware" },
          { value: "florida", label: "Florida" },
          { value: "georgia", label: "Georgia" },
          { value: "hawaii", label: "Hawaii" },
          { value: "idaho", label: "Idaho" },
          { value: "illinois", label: "Illinois" },
          { value: "indiana", label: "Indiana" },
          { value: "iowa", label: "Iowa" },
          { value: "kansas", label: "Kansas" },
          { value: "kentucky", label: "Kentucky" },
          { value: "louisiana", label: "Louisiana" },
          { value: "maine", label: "Maine" },
          { value: "maryland", label: "Maryland" },
          { value: "massachusetts", label: "Massachusetts" },
          { value: "michigan", label: "Michigan" },
          { value: "minnesota", label: "Minnesota" },
          { value: "mississippi", label: "Mississippi" },
          { value: "missouri", label: "Missouri" },
          { value: "montana", label: "Montana" },
          { value: "nebraska", label: "Nebraska" },
          { value: "nevada", label: "Nevada" },
          { value: "new_hampshire", label: "New Hampshire" },
          { value: "new_jersey", label: "New Jersey" },
          { value: "new_mexico", label: "New Mexico" },
          { value: "new_york", label: "New York" },
          { value: "north_carolina", label: "North Carolina" },
          { value: "north_dakota", label: "North Dakota" },
          { value: "ohio", label: "Ohio" },
          { value: "oklahoma", label: "Oklahoma" },
          { value: "oregon", label: "Oregon" },
          { value: "pennsylvania", label: "Pennsylvania" },
          { value: "rhode_island", label: "Rhode Island" },
          { value: "south_carolina", label: "South Carolina" },
          { value: "south_dakota", label: "South Dakota" },
          { value: "tennessee", label: "Tennessee" },
          { value: "texas", label: "Texas" },
          { value: "utah", label: "Utah" },
          { value: "vermont", label: "Vermont" },
          { value: "virginia", label: "Virginia" },
          { value: "washington", label: "Washington" },
          { value: "west_virginia", label: "West Virginia" },
          { value: "wisconsin", label: "Wisconsin" },
          { value: "wyoming", label: "Wyoming" },
          { value: "dc", label: "Washington D.C." },
        ],
      },
      {
        value: "canada",
        label: "Canada",
        states: [
          { value: "ontario", label: "Ontario" },
          { value: "quebec", label: "Quebec" },
          { value: "british_columbia", label: "British Columbia" },
          { value: "alberta", label: "Alberta" },
          { value: "manitoba", label: "Manitoba" },
          { value: "saskatchewan", label: "Saskatchewan" },
          { value: "nova_scotia", label: "Nova Scotia" },
          { value: "new_brunswick", label: "New Brunswick" },
          { value: "newfoundland", label: "Newfoundland and Labrador" },
          { value: "pei", label: "Prince Edward Island" },
          { value: "northwest_territories", label: "Northwest Territories" },
          { value: "yukon", label: "Yukon" },
          { value: "nunavut", label: "Nunavut" },
        ],
      },
      {
        value: "mexico",
        label: "Mexico",
        states: [
          { value: "cdmx", label: "Ciudad de México" },
          { value: "jalisco", label: "Jalisco" },
          { value: "nuevo_leon", label: "Nuevo León" },
          { value: "queretaro", label: "Querétaro" },
          { value: "puebla", label: "Puebla" },
          { value: "guanajuato", label: "Guanajuato" },
          { value: "chihuahua", label: "Chihuahua" },
          { value: "yucatan", label: "Yucatán" },
          { value: "baja_california", label: "Baja California" },
          { value: "sonora", label: "Sonora" },
          { value: "veracruz", label: "Veracruz" },
          { value: "mexico_state", label: "State of Mexico" },
        ],
      },
      {
        value: "antigua_and_barbuda",
        label: "Antigua and Barbuda",
        states: [
          { value: "st_john", label: "St. John's" },
          { value: "parish_of_saint_mary", label: "Saint Mary" },
          { value: "parish_of_saint_paul", label: "Saint Paul" },
          { value: "parish_of_saint_george", label: "Saint George" },
          { value: "barbuda", label: "Barbuda" },
        ],
      },
      {
        value: "bahamas",
        label: "Bahamas",
        states: [
          { value: "nassau", label: "Nassau" },
          { value: "freeport", label: "Freeport" },
          { value: "west_grand_bahama", label: "West Grand Bahama" },
          { value: "abaco", label: "Abaco" },
          { value: "eleuthera", label: "Eleuthera" },
          { value: "andros", label: "Andros" },
        ],
      },
      {
        value: "barbados",
        label: "Barbados",
        states: [
          { value: "bridgetown", label: "Bridgetown" },
          { value: "speightstown", label: "Speightstown" },
          { value: "holetown", label: "Holetown" },
          { value: "oistins", label: "Oistins" },
          { value: "bathsheba", label: "Bathsheba" },
        ],
      },
      {
        value: "belize",
        label: "Belize",
        states: [
          { value: "belize_district", label: "Belize District" },
          { value: "cayo", label: "Cayo" },
          { value: "corozal", label: "Corozal" },
          { value: "orange_walk", label: "Orange Walk" },
          { value: "stann_creek", label: "Stann Creek" },
          { value: "toledo", label: "Toledo" },
        ],
      },
      {
        value: "costa_rica",
        label: "Costa Rica",
        states: [
          { value: "san_jose", label: "San José" },
          { value: "alajuela", label: "Alajuela" },
          { value: "cartago", label: "Cartago" },
          { value: "heredia", label: "Heredia" },
          { value: "puntarenas", label: "Puntarenas" },
          { value: "limon", label: "Limón" },
          { value: "guanacaste", label: "Guanacaste" },
        ],
      },
      {
        value: "cuba",
        label: "Cuba",
        states: [
          { value: "havana", label: "Havana" },
          { value: "santiago_de_cuba", label: "Santiago de Cuba" },
          { value: "camaguey", label: "Camagüey" },
          { value: "holguin", label: "Holguín" },
          { value: "santa_clara", label: "Santa Clara" },
          { value: "cienfuegos", label: "Cienfuegos" },
          { value: "matanzas", label: "Matanzas" },
          { value: "pinar_del_rio", label: "Pinar del Río" },
        ],
      },
      {
        value: "dominica",
        label: "Dominica",
        states: [
          { value: "roseau", label: "Roseau" },
          { value: "portsmouth", label: "Portsmouth" },
          { value: "marigot", label: "Marigot" },
          { value: "grand_bay", label: "Grand Bay" },
        ],
      },
      {
        value: "dominican_republic",
        label: "Dominican Republic",
        states: [
          { value: "santo_domingo", label: "Santo Domingo" },
          { value: "santiago_dr", label: "Santiago" },
          { value: "la_vega", label: "La Vega" },
          { value: "san_pedro_de_macoris", label: "San Pedro de Macorís" },
          { value: "la_romana", label: "La Romana" },
          { value: "puerto_plata", label: "Puerto Plata" },
          { value: "higuey", label: "Higüey" },
          { value: "bonao", label: "Bonao" },
        ],
      },
      {
        value: "el_salvador",
        label: "El Salvador",
        states: [
          { value: "san_salvador", label: "San Salvador" },
          { value: "santa_ana", label: "Santa Ana" },
          { value: "san_miguel", label: "San Miguel" },
          { value: "sonsonate", label: "Sonsonate" },
          { value: "laus_Libertad", label: "La Libertad" },
          { value: "chaltenango", label: "Chalatenango" },
        ],
      },
      {
        value: "grenada",
        label: "Grenada",
        states: [
          { value: "st_george", label: "St. George" },
          { value: "st_andrew", label: "St. Andrew" },
          { value: "st_david", label: "St. David" },
          { value: "st_john_grenada", label: "St. John" },
          { value: "st_mark", label: "St. Mark" },
          { value: "st_patrick", label: "St. Patrick" },
        ],
      },
      {
        value: "guatemala",
        label: "Guatemala",
        states: [
          { value: "guatemala_city", label: "Guatemala City" },
          { value: "quetzaltenango", label: "Quetzaltenango" },
          { value: "escuintla", label: "Escuintla" },
          { value: "solola", label: "Sololá" },
          { value: "honduras_border", label: "Chiquimula" },
          { value: "peten", label: "Petén" },
          { value: "alta_verapaz", label: "Alta Verapaz" },
          { value: "suchitepequez", label: "Suchitepéquez" },
        ],
      },
      {
        value: "haiti",
        label: "Haiti",
        states: [
          { value: "port_au_prince", label: "Port-au-Prince" },
          { value: "cap_haitien", label: "Cap-Haïtien" },
          { value: "les_cayes", label: "Les Cayes" },
          { value: "gonaives", label: "Gonaïves" },
          { value: "petion_ville", label: "Pétion-Ville" },
          { value: "jacmel", label: "Jacmel" },
        ],
      },
      {
        value: "honduras",
        label: "Honduras",
        states: [
          { value: "tegucigalpa", label: "Tegucigalpa" },
          { value: "san_pedro_sula", label: "San Pedro Sula" },
          { value: "la_ceiba", label: "La Ceiba" },
          { value: "choloma", label: "Choloma" },
          { value: "comayagua", label: "Comayagua" },
          { value: "el_progreso", label: "El Progreso" },
          { value: "ticos_colon", label: "Colón" },
        ],
      },
      {
        value: "jamaica",
        label: "Jamaica",
        states: [
          { value: "kingston", label: "Kingston" },
          { value: "montego_bay", label: "Montego Bay" },
          { value: "spanish_town", label: "Spanish Town" },
          { value: "portmore", label: "Portmore" },
          { value: "mandeville", label: "Mandeville" },
          { value: "may_pen", label: "May Pen" },
          { value: "ochi_rios", label: "Ocho Rios" },
        ],
      },
      {
        value: "nicaragua",
        label: "Nicaragua",
        states: [
          { value: "managua", label: "Managua" },
          { value: "leon_nicaragua", label: "León" },
          { value: "granada_nicaragua", label: "Granada" },
          { value: "masaya", label: "Masaya" },
          { value: "matagalpa", label: "Matagalpa" },
          { value: "esteli", label: "Estelí" },
          { value: "chinandega", label: "Chinandega" },
        ],
      },
      {
        value: "panama",
        label: "Panama",
        states: [
          { value: "panama_city", label: "Panama City" },
          { value: "colon", label: "Colón" },
          { value: "david", label: "David" },
          { value: "santiago_panama", label: "Santiago" },
          { value: "chiriqui", label: "Chiriquí" },
          { value: "los_santos", label: "Los Santos" },
          { value: "cocle", label: "Coclé" },
        ],
      },
      {
        value: "saint_kitts_and_nevis",
        label: "Saint Kitts and Nevis",
        states: [
          { value: "basseterre", label: "Basseterre" },
          { value: "cayon", label: "Cayon" },
          { value: "sandy_point", label: "Sandy Point" },
          { value: "charlestown", label: "Charlestown" },
        ],
      },
      {
        value: "saint_lucia",
        label: "Saint Lucia",
        states: [
          { value: "castries", label: "Castries" },
          { value: "gros_islet", label: "Gros Islet" },
          { value: "vieux_fort", label: "Vieux Fort" },
          { value: "soufriere", label: "Soufrière" },
          { value: "micoud", label: "Micoud" },
        ],
      },
      {
        value: "saint_vincent_and_the_grenadines",
        label: "Saint Vincent and the Grenadines",
        states: [
          { value: "kingstown", label: "Kingstown" },
          { value: "georgetown_svg", label: "Georgetown" },
          { value: "barrouallie", label: "Barrouallie" },
          { value: "bequia", label: "Bequia" },
        ],
      },
      {
        value: "trinidad_and_tobago",
        label: "Trinidad and Tobago",
        states: [
          { value: "port_of_spain", label: "Port of Spain" },
          { value: "san_fernando", label: "San Fernando" },
          { value: "chaguanas", label: "Chaguanas" },
          { value: "arima", label: "Arima" },
          { value: "couva", label: "Couva" },
          { value: "scarborough", label: "Scarborough" },
        ],
      },
    ],
  },
  {
    value: "south_america",
    label: "South America",
    emoji: "🌎",
    countries: [
      {
        value: "brazil",
        label: "Brazil",
        states: [
          { value: "sao_paulo", label: "São Paulo" },
          { value: "rio_de_janeiro", label: "Rio de Janeiro" },
          { value: "minas_gerais", label: "Minas Gerais" },
          { value: "bahia", label: "Bahia" },
          { value: "parana", label: "Paraná" },
          { value: "rio_grande_do_sul", label: "Rio Grande do Sul" },
          { value: "pernambuco", label: "Pernambuco" },
          { value: "ceara", label: "Ceará" },
          { value: "goias", label: "Goiás" },
          { value: "distrito_federal", label: "Distrito Federal" },
          { value: "santa_catarina", label: "Santa Catarina" },
          { value: "amazonas", label: "Amazonas" },
          { value: "para", label: "Pará" },
          { value: "maranhao", label: "Maranhão" },
          { value: "rio_grande_do_norte", label: "Rio Grande do Norte" },
          { value: "espirito_santo", label: "Espírito Santo" },
          { value: "mato_grosso", label: "Mato Grosso" },
          { value: "mato_grosso_do_sul", label: "Mato Grosso do Sul" },
        ],
      },
      {
        value: "argentina",
        label: "Argentina",
        states: [
          { value: "buenos_aires", label: "Buenos Aires" },
          { value: "cordoba", label: "Córdoba" },
          { value: "santa_fe", label: "Santa Fe" },
          { value: "mendoza", label: "Mendoza" },
          { value: "tucuman", label: "Tucumán" },
          { value: "rosario", label: "Rosario" },
          { value: "salta", label: "Salta" },
          { value: "misiones", label: "Misiones" },
          { value: "chaco", label: "Chaco" },
          { value: "corrientes", label: "Corrientes" },
          { value: "neuquen", label: "Neuquén" },
          { value: "rio_negro", label: "Río Negro" },
          { value: "tierra_del_fuego", label: "Tierra del Fuego" },
          { value: "san_luis", label: "San Luis" },
          { value: "san_juan_ar", label: "San Juan" },
        ],
      },
      {
        value: "colombia",
        label: "Colombia",
        states: [
          { value: "bogota", label: "Bogotá" },
          { value: "antioquia", label: "Antioquia" },
          { value: "valle_del_cauca", label: "Valle del Cauca" },
          { value: "cundinamarca", label: "Cundinamarca" },
          { value: "santander", label: "Santander" },
          { value: "atlantico", label: "Atlántico" },
          { value: "bolivar", label: "Bolívar" },
          { value: "narino", label: "Nariño" },
          { value: "cordoba_col", label: "Córdoba" },
          { value: "boyaca", label: "Boyacá" },
          { value: "magdalena", label: "Magdalena" },
          { value: "cesar", label: "Cesar" },
          { value: "meta", label: "Meta" },
          { value: "huila", label: "Huila" },
          { value: "risaralda", label: "Risaralda" },
        ],
      },
      {
        value: "chile",
        label: "Chile",
        states: [
          { value: "santiago", label: "Santiago" },
          { value: "valparaiso", label: "Valparaíso" },
          { value: "concepcion", label: "Concepción" },
          { value: "atacama", label: "Atacama" },
          { value: "biobio", label: "Biobío" },
          { value: "araucania", label: "La Araucanía" },
          { value: "los_lagos", label: "Los Lagos" },
          { value: "magallanes", label: "Magallanes" },
          { value: "coquimbo", label: "Coquimbo" },
          { value: "maule", label: "Maule" },
          { value: "ohiggins", label: "O'Higgins" },
        ],
      },
      {
        value: "peru",
        label: "Peru",
        states: [
          { value: "lima", label: "Lima" },
          { value: "cusco", label: "Cusco" },
          { value: "arequipa", label: "Arequipa" },
          { value: "trujillo", label: "Trujillo" },
          { value: "piura", label: "Piura" },
          { value: "junin", label: "Junín" },
          { value: "loreto", label: "Loreto" },
          { value: "ancahs", label: "Áncash" },
          { value: "cusco_region", label: "Cusco Region" },
          { value: "la_libertad", label: "La Libertad" },
          { value: "lambayeque", label: "Lambayeque" },
        ],
      },
      {
        value: "bolivia",
        label: "Bolivia",
        states: [
          { value: "la_paz", label: "La Paz" },
          { value: "santa_cruz", label: "Santa Cruz" },
          { value: "cochabamba", label: "Cochabamba" },
          { value: "sucre", label: "Sucre" },
          { value: "oruro", label: "Oruro" },
          { value: "potosi", label: "Potosí" },
          { value: "tarija", label: "Tarija" },
          { value: "beni", label: "Beni" },
          { value: "pando", label: "Pando" },
        ],
      },
      {
        value: "ecuador",
        label: "Ecuador",
        states: [
          { value: "quito", label: "Quito" },
          { value: "guayaquil", label: "Guayaquil" },
          { value: "cuenca", label: "Cuenca" },
          { value: "manabi", label: "Manabí" },
          { value: "los_rios", label: "Los Ríos" },
          { value: "azuay", label: "Azuay" },
          { value: "tungurahua", label: "Tungurahua" },
          { value: "el_oro", label: "El Oro" },
          { value: "santo_domingo", label: "Santo Domingo" },
        ],
      },
      {
        value: "guyana",
        label: "Guyana",
        states: [
          { value: "georgetown", label: "Georgetown" },
          { value: "new_amsterdam", label: "New Amsterdam" },
          { value: "bartica", label: "Bartica" },
          { value: "linden", label: "Linden" },
          { value: "essequibo", label: "Essequibo" },
          { value: "berbice", label: "Berbice" },
        ],
      },
      {
        value: "paraguay",
        label: "Paraguay",
        states: [
          { value: "asuncion", label: "Asunción" },
          { value: "ciudad_del_este", label: "Ciudad del Este" },
          { value: "encarnacion", label: "Encarnación" },
          { value: "concepcion_py", label: "Concepción" },
          { value: "pedro_juan_caballero", label: "Pedro Juan Caballero" },
          { value: "altos_parana", label: "Alto Paraná" },
          { value: "caaguazu", label: "Caaguazú" },
          { value: "itapua", label: "Itapúa" },
        ],
      },
      {
        value: "suriname",
        label: "Suriname",
        states: [
          { value: "paramaribo", label: "Paramaribo" },
          { value: "nickerie", label: "Nickerie" },
          { value: "coronie", label: "Coronie" },
          { value: "saramacca", label: "Saramacca" },
          { value: "wanica", label: "Wanica" },
          { value: "marowijne", label: "Marowijne" },
        ],
      },
      {
        value: "uruguay",
        label: "Uruguay",
        states: [
          { value: "montevideo", label: "Montevideo" },
          { value: "punta_del_este", label: "Punta del Este" },
          { value: "salto", label: "Salto" },
          { value: "paysandu", label: "Paysandú" },
          { value: "rivera", label: "Rivera" },
          { value: "maldonado", label: "Maldonado" },
          { value: "canelones", label: "Canelones" },
          { value: "rocha", label: "Rocha" },
        ],
      },
      {
        value: "venezuela",
        label: "Venezuela",
        states: [
          { value: "caracas", label: "Caracas" },
          { value: "maracaibo", label: "Maracaibo" },
          { value: "valencia_ve", label: "Valencia" },
          { value: "barquisimeto", label: "Barquisimeto" },
          { value: "maracay", label: "Maracay" },
          { value: "zulia", label: "Zulia" },
          { value: "miranda", label: "Miranda" },
          { value: "carabobo", label: "Carabobo" },
          { value: "aragua", label: "Aragua" },
          { value: "lara", label: "Lara" },
          { value: "bolivar_ve", label: "Bolívar" },
          { value: "tachira", label: "Táchira" },
          { value: "anzoategui", label: "Anzoátegui" },
          { value: "monagas", label: "Monagas" },
          { value: "sucre_ve", label: "Sucre" },
        ],
      },
    ],
  },
  {
    value: "europe",
    label: "Europe",
    emoji: "🇪🇺",
    countries: [
      {
        value: "uk",
        label: "United Kingdom",
        states: [
          { value: "england", label: "England" },
          { value: "scotland", label: "Scotland" },
          { value: "wales", label: "Wales" },
          { value: "northern_ireland", label: "Northern Ireland" },
          { value: "london", label: "Greater London" },
          { value: "manchester", label: "Greater Manchester" },
          { value: "birmingham", label: "West Midlands" },
          { value: "leeds", label: "West Yorkshire" },
          { value: "edinburgh", label: "Edinburgh" },
        ],
      },
      {
        value: "germany",
        label: "Germany",
        states: [
          { value: "bavaria", label: "Bavaria" },
          { value: "berlin", label: "Berlin" },
          { value: "hamburg", label: "Hamburg" },
          { value: "hesse", label: "Hesse" },
          { value: "north_rhine_westphalia", label: "North Rhine-Westphalia" },
          { value: "baden_wurttemberg", label: "Baden-Württemberg" },
          { value: "saxony", label: "Saxony" },
          { value: "lower_saxony", label: "Lower Saxony" },
          { value: "rhineland_palatinate", label: "Rhineland-Palatinate" },
          { value: "bremen", label: "Bremen" },
        ],
      },
      {
        value: "france",
        label: "France",
        states: [
          { value: "ile_de_france", label: "Île-de-France" },
          { value: "provence_alpes_cote_dazur", label: "Provence-Alpes-Côte d'Azur" },
          { value: "auvergne_rhone_alpes", label: "Auvergne-Rhône-Alpes" },
          { value: "occitanie", label: "Occitanie" },
          { value: "nouvelle_aquitaine", label: "Nouvelle-Aquitaine" },
          { value: "hauts_de_france", label: "Hauts-de-France" },
          { value: "brittany", label: "Brittany" },
          { value: "normandy", label: "Normandy" },
        ],
      },
      {
        value: "spain",
        label: "Spain",
        states: [
          { value: "madrid", label: "Madrid" },
          { value: "catalonia", label: "Catalonia" },
          { value: "andalusia", label: "Andalusia" },
          { value: "valencia", label: "Valencia" },
          { value: "basque_country", label: "Basque Country" },
          { value: "galicia", label: "Galicia" },
        ],
      },
      {
        value: "italy",
        label: "Italy",
        states: [
          { value: "lazio", label: "Lazio" },
          { value: "lombardy", label: "Lombardy" },
          { value: "campania", label: "Campania" },
          { value: "veneto", label: "Veneto" },
          { value: "emilia_romagna", label: "Emilia-Romagna" },
          { value: "tuscany", label: "Tuscany" },
          { value: "piedmont", label: "Piedmont" },
          { value: "sicily", label: "Sicily" },
        ],
      },
      {
        value: "netherlands",
        label: "Netherlands",
        states: [
          { value: "north_holland", label: "North Holland" },
          { value: "south_holland", label: "South Holland" },
          { value: "utrecht", label: "Utrecht" },
          { value: "north_brabant", label: "North Brabant" },
          { value: "gelderland", label: "Gelderland" },
        ],
      },
      {
        value: "sweden",
        label: "Sweden",
        states: [
          { value: "stockholm", label: "Stockholm" },
          { value: "vastra_gotaland", label: "Västra Götaland" },
          { value: "skane", label: "Skåne" },
          { value: "uppsala", label: "Uppsala" },
        ],
      },
      {
        value: "switzerland",
        label: "Switzerland",
        states: [
          { value: "zurich", label: "Zurich" },
          { value: "geneva", label: "Geneva" },
          { value: "bern", label: "Bern" },
          { value: "basel", label: "Basel" },
          { value: "lausanne", label: "Lausanne" },
        ],
      },
      {
        value: "ireland",
        label: "Ireland",
        states: [
          { value: "dublin", label: "Dublin" },
          { value: "cork", label: "Cork" },
          { value: "galway", label: "Galway" },
          { value: "limerick", label: "Limerick" },
        ],
      },
      {
        value: "portugal",
        label: "Portugal",
        states: [
          { value: "lisbon", label: "Lisbon" },
          { value: "porto", label: "Porto" },
          { value: "algarve", label: "Algarve" },
          { value: "madeira", label: "Madeira" },
        ],
      },
      {
        value: "poland",
        label: "Poland",
        states: [
          { value: "mazowieckie", label: "Masovian" },
          { value: "slaskie", label: "Silesian" },
          { value: "wielkopolskie", label: "Greater Poland" },
          { value: "malopolskie", label: "Lesser Poland" },
        ],
      },
      {
        value: "austria",
        label: "Austria",
        states: [
          { value: "vienna", label: "Vienna" },
          { value: "styria", label: "Styria" },
          { value: "upper_austria", label: "Upper Austria" },
          { value: "tyrol", label: "Tyrol" },
          { value: "carinthia", label: "Carinthia" },
          { value: "salzburg", label: "Salzburg" },
          { value: "vorarlberg", label: "Vorarlberg" },
          { value: "burgenland", label: "Burgenland" },
          { value: "lower_austria", label: "Lower Austria" },
        ],
      },
      {
        value: "belgium",
        label: "Belgium",
        states: [
          { value: "brussels", label: "Brussels-Capital" },
          { value: "flanders", label: "Flanders" },
          { value: "wallonia", label: "Wallonia" },
          { value: "antwerp", label: "Antwerp" },
          { value: "east_flanders", label: "East Flanders" },
          { value: "west_flanders", label: "West Flanders" },
          { value: "hainaut", label: "Hainaut" },
          { value: "liege", label: "Liège" },
          { value: "limburg_be", label: "Limburg" },
          { value: "namur", label: "Namur" },
        ],
      },
      {
        value: "bulgaria",
        label: "Bulgaria",
        states: [
          { value: "sofia", label: "Sofia" },
          { value: "plovdiv", label: "Plovdiv" },
          { value: "varna", label: "Varna" },
          { value: "burgas", label: "Burgas" },
          { value: "ruse", label: "Ruse" },
          { value: "stara_zagora", label: "Stara Zagora" },
          { value: "pleven", label: "Pleven" },
        ],
      },
      {
        value: "croatia",
        label: "Croatia",
        states: [
          { value: "zagreb", label: "Zagreb" },
          { value: "split", label: "Split" },
          { value: "rijeka", label: "Rijeka" },
          { value: "osijek", label: "Osijek" },
          { value: "dubrovnik", label: "Dubrovnik" },
          { value: "zadar", label: "Zadar" },
          { value: "pula", label: "Pula" },
        ],
      },
      {
        value: "czech_republic",
        label: "Czech Republic",
        states: [
          { value: "prague", label: "Prague" },
          { value: "brno", label: "Brno" },
          { value: "ostrava", label: "Ostrava" },
          { value: "plzen", label: "Plzeň" },
          { value: "liberec", label: "Liberec" },
          { value: "olomouc", label: "Olomouc" },
          { value: "ceske_budejovice", label: "České Budějovice" },
          { value: "hradec_kralove", label: "Hradec Králové" },
        ],
      },
      {
        value: "denmark",
        label: "Denmark",
        states: [
          { value: "copenhagen", label: "Copenhagen" },
          { value: "aarhus", label: "Aarhus" },
          { value: "odense", label: "Odense" },
          { value: "aalborg", label: "Aalborg" },
          { value: "esbjerg", label: "Esbjerg" },
          { value: "roskilde", label: "Roskilde" },
        ],
      },
      {
        value: "estonia",
        label: "Estonia",
        states: [
          { value: "harju", label: "Harju" },
          { value: "tartu", label: "Tartu" },
          { value: "ida_viru", label: "Ida-Viru" },
          { value: "parnu", label: "Pärnu" },
          { value: "laane_viru", label: "Lääne-Viru" },
          { value: "viljandi", label: "Viljandi" },
        ],
      },
      {
        value: "finland",
        label: "Finland",
        states: [
          { value: "uusimaa", label: "Uusimaa" },
          { value: "pirkanmaa", label: "Pirkanmaa" },
          { value: "varsinais_suomi", label: "Varsinais-Suomi" },
          { value: "ostrobothnia", label: "Ostrobothnia" },
          { value: "north_ostrobothnia", label: "North Ostrobothnia" },
          { value: "lapland_fi", label: "Lapland" },
          { value: "kymenlaakso", label: "Kymenlaakso" },
        ],
      },
      {
        value: "greece",
        label: "Greece",
        states: [
          { value: "attica", label: "Attica" },
          { value: "central_macedonia", label: "Central Macedonia" },
          { value: "thessaly", label: "Thessaly" },
          { value: "crete", label: "Crete" },
          { value: "epirus", label: "Epirus" },
          { value: "western_greece", label: "Western Greece" },
          { value: "peloponnese", label: "Peloponnese" },
          { value: "ionian_islands", label: "Ionian Islands" },
          { value: "south_aegean", label: "South Aegean" },
        ],
      },
      {
        value: "hungary",
        label: "Hungary",
        states: [
          { value: "budapest", label: "Budapest" },
          { value: "pest_county", label: "Pest County" },
          { value: "gyor_moson_sopron", label: "Győr-Moson-Sopron" },
          { value: "baranya", label: "Baranya" },
          { value: "bajakiskun", label: "Bács-Kiskun" },
          { value: "hajdu_bihar", label: "Hajdú-Bihar" },
          { value: "csongrad_csanad", label: "Csongrád-Csanád" },
          { value: "veszprem", label: "Veszprém" },
        ],
      },
      {
        value: "iceland",
        label: "Iceland",
        states: [
          { value: "reykjavik", label: "Reykjavík" },
          { value: "kopavogur", label: "Kópavogur" },
          { value: "hafnarfjordur", label: "Hafnarfjörður" },
          { value: "akureyri", label: "Akureyri" },
          { value: "reykjanes", label: "Reykjanes" },
          { value: "south_iceland", label: "Southern Peninsula" },
        ],
      },
      {
        value: "latvia",
        label: "Latvia",
        states: [
          { value: "riga", label: "Riga" },
          { value: "dzintari", label: "Jūrmala" },
          { value: "daugavpils", label: "Daugavpils" },
          { value: "liepaja", label: "Liepāja" },
          { value: "jelgava", label: "Jelgava" },
          { value: "rezekne", label: "Rēzekne" },
        ],
      },
      {
        value: "liechtenstein",
        label: "Liechtenstein",
        states: [
          { value: "vaduz", label: "Vaduz" },
          { value: "schaan", label: "Schaan" },
          { value: "triesen", label: "Triesen" },
          { value: "balzers", label: "Balzers" },
          { value: "eschen", label: "Eschen" },
        ],
      },
      {
        value: "lithuania",
        label: "Lithuania",
        states: [
          { value: "vilnius", label: "Vilnius" },
          { value: "kaunas", label: "Kaunas" },
          { value: "klaipeda", label: "Klaipėda" },
          { value: "siauliai", label: "Šiauliai" },
          { value: "panevezys", label: "Panevėžys" },
          { value: "alytus", label: "Alytus" },
        ],
      },
      {
        value: "luxembourg",
        label: "Luxembourg",
        states: [
          { value: "luxembourg_city", label: "Luxembourg City" },
          { value: "esch_sur_alzette", label: "Esch-sur-Alzette" },
          { value: "differdange", label: "Differdange" },
          { value: "dudelange", label: "Dudelange" },
          { value: "eich", label: "Eich" },
        ],
      },
      {
        value: "malta",
        label: "Malta",
        states: [
          { value: "valletta", label: "Valletta" },
          { value: "sliema", label: "Sliema" },
          { value: "st_julians", label: "St. Julian's" },
          { value: "mosta", label: "Mosta" },
          { value: "rabat_malta", label: "Rabat" },
          { value: "gozo", label: "Gozo" },
        ],
      },
      {
        value: "monaco",
        label: "Monaco",
        states: [
          { value: "monte_carlo", label: "Monte Carlo" },
          { value: "la_condamine", label: "La Condamine" },
          { value: "fontvieille", label: "Fontvieille" },
          { value: "monaco_ville", label: "Monaco-Ville" },
        ],
      },
      {
        value: "montenegro",
        label: "Montenegro",
        states: [
          { value: "podgorica", label: "Podgorica" },
          { value: "niksic", label: "Nikšić" },
          { value: "herceg_novi", label: "Herceg Novi" },
          { value: "budva", label: "Budva" },
          { value: "kotor", label: "Kotor" },
          { value: "bar_me", label: "Bar" },
        ],
      },
      {
        value: "north_macedonia",
        label: "North Macedonia",
        states: [
          { value: "skopje", label: "Skopje" },
          { value: "bitola", label: "Bitola" },
          { value: "kumanovo", label: "Kumanovo" },
          { value: "prilep", label: "Prilep" },
          { value: "tetovo", label: "Tetovo" },
          { value: "ohrid", label: "Ohrid" },
        ],
      },
      {
        value: "norway",
        label: "Norway",
        states: [
          { value: "oslo", label: "Oslo" },
          { value: "bergen", label: "Bergen" },
          { value: "trondheim", label: "Trondheim" },
          { value: "stavanger", label: "Stavanger" },
          { value: "tromso", label: "Tromsø" },
          { value: "drammen", label: "Drammen" },
          { value: "kristiansand", label: "Kristiansand" },
          { value: "bodo", label: "Bodø" },
        ],
      },
      {
        value: "romania",
        label: "Romania",
        states: [
          { value: "bucharest", label: "Bucharest" },
          { value: "cluj", label: "Cluj" },
          { value: "timis", label: "Timiș" },
          { value: "iasi", label: "Iași" },
          { value: "constanta_ro", label: "Constanța" },
          { value: "brasov", label: "Brașov" },
          { value: "sibiu", label: "Sibiu" },
          { value: "galati", label: "Galați" },
          { value: "iasi_county", label: "Iași County" },
          { value: "dolj", label: "Dolj" },
        ],
      },
      {
        value: "san_marino",
        label: "San Marino",
        states: [
          { value: "san_marino_city", label: "City of San Marino" },
          { value: "borgo_maggiore", label: "Borgo Maggiore" },
          { value: "serrat", label: "Serravalle" },
          { value: "domagnano", label: "Domagnano" },
          { value: "fiorentino", label: "Fiorentino" },
        ],
      },
      {
        value: "serbia",
        label: "Serbia",
        states: [
          { value: "belgrade", label: "Belgrade" },
          { value: "novi_sad", label: "Novi Sad" },
          { value: "nis", label: "Niš" },
          { value: "kragujevac", label: "Kragujevac" },
          { value: "subotica", label: "Subotica" },
          { value: "leskovac", label: "Leskovac" },
          { value: "cacak", label: "Čačak" },
          { value: "novi_pazar", label: "Novi Pazar" },
        ],
      },
      {
        value: "slovakia",
        label: "Slovakia",
        states: [
          { value: "bratislava", label: "Bratislava" },
          { value: "kosice", label: "Košice" },
          { value: "presov", label: "Prešov" },
          { value: "zilina", label: "Žilina" },
          { value: "nitra", label: "Nitra" },
          { value: "banska_bystrica", label: "Banská Bystrica" },
          { value: "trnava", label: "Trnava" },
          { value: "trencin", label: "Trenčín" },
        ],
      },
      {
        value: "slovenia",
        label: "Slovenia",
        states: [
          { value: "ljubljana", label: "Ljubljana" },
          { value: "maribor", label: "Maribor" },
          { value: "celje", label: "Celje" },
          { value: "kranj", label: "Kranj" },
          { value: "koper", label: "Koper" },
          { value: "novo_mesto", label: "Novo Mesto" },
        ],
      },
      {
        value: "ukraine",
        label: "Ukraine",
        states: [
          { value: "kyiv", label: "Kyiv" },
          { value: "kharkiv", label: "Kharkiv" },
          { value: "odesa", label: "Odesa" },
          { value: "dnipro", label: "Dnipro" },
          { value: "donetsk", label: "Donetsk" },
          { value: "zaporizhzhia", label: "Zaporizhzhia" },
          { value: "lviv", label: "Lviv" },
          { value: "kryvyi_rih", label: "Kryvyi Rih" },
          { value: "mykolaiv", label: "Mykolaiv" },
          { value: "mariupol", label: "Mariupol" },
          { value: "vinnytsia", label: "Vinnytsia" },
          { value: "poltava", label: "Poltava" },
          { value: "chernihiv", label: "Chernihiv" },
          { value: "ivano_frankivsk", label: "Ivano-Frankivsk" },
          { value: "ternopil", label: "Ternopil" },
        ],
      },
    ],
  },
  {
    value: "asia",
    label: "Asia",
    emoji: "🌏",
    countries: [
      {
        value: "india",
        label: "India",
        states: [
          { value: "maharashtra", label: "Maharashtra" },
          { value: "karnataka", label: "Karnataka" },
          { value: "tamil_nadu", label: "Tamil Nadu" },
          { value: "telangana", label: "Telangana" },
          { value: "gujarat", label: "Gujarat" },
          { value: "delhi", label: "Delhi" },
          { value: "west_bengal", label: "West Bengal" },
          { value: "rajasthan", label: "Rajasthan" },
          { value: "kerala", label: "Kerala" },
          { value: "uttar_pradesh", label: "Uttar Pradesh" },
          { value: "madhya_pradesh", label: "Madhya Pradesh" },
          { value: "haryana", label: "Haryana" },
          { value: "punjab", label: "Punjab" },
          { value: "andhra_pradesh", label: "Andhra Pradesh" },
          { value: "odisha", label: "Odisha" },
          { value: "bihar", label: "Bihar" },
          { value: "jharkhand", label: "Jharkhand" },
          { value: "chhattisgarh", label: "Chhattisgarh" },
          { value: "goa", label: "Goa" },
          { value: "assam", label: "Assam" },
          { value: "himachal_pradesh", label: "Himachal Pradesh" },
          { value: "uttarakhand", label: "Uttarakhand" },
          { value: "meghalaya", label: "Meghalaya" },
          { value: "manipur", label: "Manipur" },
          { value: "nagaland", label: "Nagaland" },
        ],
      },
      {
        value: "china",
        label: "China",
        states: [
          { value: "guangdong", label: "Guangdong" },
          { value: "shanghai", label: "Shanghai" },
          { value: "beijing", label: "Beijing" },
          { value: "zhejiang", label: "Zhejiang" },
          { value: "jiangsu", label: "Jiangsu" },
          { value: "sichuan", label: "Sichuan" },
          { value: "hubei", label: "Hubei" },
          { value: "fujian", label: "Fujian" },
          { value: "shandong", label: "Shandong" },
          { value: "henan", label: "Henan" },
          { value: "hunan", label: "Hunan" },
          { value: "anhui", label: "Anhui" },
          { value: "hebei", label: "Hebei" },
          { value: "shaanxi", label: "Shaanxi" },
          { value: "jiangxi", label: "Jiangxi" },
          { value: "liaoning", label: "Liaoning" },
          { value: "chongqing", label: "Chongqing" },
          { value: "tianjin", label: "Tianjin" },
          { value: "yunnan", label: "Yunnan" },
          { value: "guangxi", label: "Guangxi" },
        ],
      },
      {
        value: "japan",
        label: "Japan",
        states: [
          { value: "tokyo", label: "Tokyo" },
          { value: "osaka", label: "Osaka" },
          { value: "kanagawa", label: "Kanagawa" },
          { value: "aichi", label: "Aichi" },
          { value: "fukuoka", label: "Fukuoka" },
          { value: "hyogo", label: "Hyōgo" },
          { value: "hokkaido", label: "Hokkaido" },
          { value: "kyoto", label: "Kyoto" },
          { value: "saitama", label: "Saitama" },
          { value: "chiba", label: "Chiba" },
        ],
      },
      {
        value: "uae",
        label: "United Arab Emirates",
        states: [
          { value: "dubai", label: "Dubai" },
          { value: "abu_dhabi", label: "Abu Dhabi" },
          { value: "sharjah", label: "Sharjah" },
          { value: "ajman", label: "Ajman" },
          { value: "ras_al_khaimah", label: "Ras Al Khaimah" },
          { value: "fujairah", label: "Fujairah" },
          { value: "umm_al_quwain", label: "Umm Al Quwain" },
        ],
      },
      {
        value: "singapore",
        label: "Singapore",
        states: [
          { value: "central_region", label: "Central Region" },
          { value: "east_region", label: "East Region" },
          { value: "north_region", label: "North Region" },
          { value: "north_east_region", label: "North-East Region" },
          { value: "west_region", label: "West Region" },
        ],
      },
      {
        value: "south_korea",
        label: "South Korea",
        states: [
          { value: "seoul", label: "Seoul" },
          { value: "busan", label: "Busan" },
          { value: "incheon", label: "Incheon" },
          { value: "daegu", label: "Daegu" },
          { value: "daejeon", label: "Daejeon" },
          { value: "gwangju", label: "Gwangju" },
        ],
      },
      {
        value: "saudi_arabia",
        label: "Saudi Arabia",
        states: [
          { value: "riyadh", label: "Riyadh" },
          { value: "jeddah", label: "Jeddah" },
          { value: "makkah", label: "Makkah" },
          { value: "dammam", label: "Dammam" },
          { value: "madinah", label: "Madinah" },
        ],
      },
      {
        value: "israel",
        label: "Israel",
        states: [
          { value: "tel_aviv", label: "Tel Aviv" },
          { value: "jerusalem", label: "Jerusalem" },
          { value: "haifa", label: "Haifa" },
          { value: "beersheva", label: "Be'er Sheva" },
        ],
      },
      {
        value: "thailand",
        label: "Thailand",
        states: [
          { value: "bangkok", label: "Bangkok" },
          { value: "chiang_mai", label: "Chiang Mai" },
          { value: "phuket", label: "Phuket" },
          { value: "pattaya", label: "Pattaya" },
        ],
      },
      {
        value: "indonesia",
        label: "Indonesia",
        states: [
          { value: "jakarta", label: "Jakarta" },
          { value: "bali", label: "Bali" },
          { value: "surabaya", label: "Surabaya" },
          { value: "bandung", label: "Bandung" },
          { value: "medan", label: "Medan" },
          { value: "semarang", label: "Semarang" },
          { value: "makassar", label: "Makassar" },
          { value: "palembang", label: "Palembang" },
          { value: "yogyakarta", label: "Yogyakarta" },
          { value: "malang", label: "Malang" },
        ],
      },
      {
        value: "philippines",
        label: "Philippines",
        states: [
          { value: "metro_manila", label: "Metro Manila" },
          { value: "cebu", label: "Cebu" },
          { value: "davao", label: "Davao" },
          { value: "quezon_city", label: "Quezon City" },
        ],
      },
      {
        value: "malaysia",
        label: "Malaysia",
        states: [
          { value: "kuala_lumpur", label: "Kuala Lumpur" },
          { value: "selangor", label: "Selangor" },
          { value: "penang", label: "Penang" },
          { value: "johor", label: "Johor" },
        ],
      },
      {
        value: "turkey",
        label: "Turkey",
        states: [
          { value: "istanbul", label: "Istanbul" },
          { value: "ankara", label: "Ankara" },
          { value: "izmir", label: "Izmir" },
          { value: "antalya", label: "Antalya" },
          { value: "bursa", label: "Bursa" },
        ],
      },
      {
        value: "afghanistan",
        label: "Afghanistan",
        states: [
          { value: "kabul", label: "Kabul" },
          { value: "herat", label: "Herat" },
          { value: "mazar_i_sharif", label: "Mazar-i-Sharif" },
          { value: "kandahar", label: "Kandahar" },
          { value: "jalalabad", label: "Jalalabad" },
          { value: "kunduz", label: "Kunduz" },
          { value: "ghazni", label: "Ghazni" },
          { value: "bamyan", label: "Bamyan" },
        ],
      },
      {
        value: "armenia",
        label: "Armenia",
        states: [
          { value: "yerevan", label: "Yerevan" },
          { value: "gyumri", label: "Gyumri" },
          { value: "vanadzor", label: "Vanadzor" },
          { value: "ararat", label: "Ararat" },
          { value: "kotayk", label: "Kotayk" },
          { value: "shirak", label: "Shirak" },
        ],
      },
      {
        value: "azerbaijan",
        label: "Azerbaijan",
        states: [
          { value: "baku", label: "Baku" },
          { value: "ganja", label: "Ganja" },
          { value: "sumgait", label: "Sumqayit" },
          { value: "lankaran", label: "Lankaran" },
          { value: "shaki", label: "Shaki" },
          { value: "mingachevir", label: "Mingachevir" },
        ],
      },
      {
        value: "bahrain",
        label: "Bahrain",
        states: [
          { value: "manama", label: "Manama" },
          { value: "muharraq", label: "Muharraq" },
          { value: "riffa", label: "Riffa" },
          { value: "hamad_town", label: "Hamad Town" },
          { value: "isa_town", label: "Isa Town" },
        ],
      },
      {
        value: "bangladesh",
        label: "Bangladesh",
        states: [
          { value: "dhaka", label: "Dhaka" },
          { value: "chittagong", label: "Chittagong" },
          { value: "khulna", label: "Khulna" },
          { value: "rajshahi", label: "Rajshahi" },
          { value: "sylhet", label: "Sylhet" },
          { value: "rangpur", label: "Rangpur" },
          { value: "barisal", label: "Barisal" },
          { value: "mymensingh", label: "Mymensingh" },
          { value: "comilla", label: "Comilla" },
          { value: "gazipur", label: "Gazipur" },
        ],
      },
      {
        value: "bhutan",
        label: "Bhutan",
        states: [
          { value: "thimphu", label: "Thimphu" },
          { value: "paro", label: "Paro" },
          { value: "punakha", label: "Punakha" },
          { value: "wangdue_phodrang", label: "Wangdue Phodrang" },
          { value: "trashigang", label: "Trashigang" },
        ],
      },
      {
        value: "brunei",
        label: "Brunei",
        states: [
          { value: "bandar_seri_begawan", label: "Bandar Seri Begawan" },
          { value: "kuala_belait", label: "Kuala Belait" },
          { value: "tutong", label: "Tutong" },
          { value: "temburong", label: "Temburong" },
        ],
      },
      {
        value: "cambodia",
        label: "Cambodia",
        states: [
          { value: "phnom_penh", label: "Phnom Penh" },
          { value: "siem_reap", label: "Siem Reap" },
          { value: "battambang", label: "Battambang" },
          { value: "sihanoukville", label: "Sihanoukville" },
          { value: "kampot", label: "Kampot" },
          { value: "takeo", label: "Takeo" },
          { value: "kampong_cham", label: "Kampong Cham" },
        ],
      },
      {
        value: "georgia_country",
        label: "Georgia",
        states: [
          { value: "tbilisi", label: "Tbilisi" },
          { value: "batumi", label: "Batumi" },
          { value: "kutaisi", label: "Kutaisi" },
          { value: "rustavi", label: "Rustavi" },
          { value: "sukhumi", label: "Sukhumi" },
          { value: "gori", label: "Gori" },
        ],
      },
      {
        value: "iraq",
        label: "Iraq",
        states: [
          { value: "baghdad", label: "Baghdad" },
          { value: "basra", label: "Basra" },
          { value: "erbil", label: "Erbil" },
          { value: "mosul", label: "Mosul" },
          { value: "kirkuk", label: "Kirkuk" },
          { value: "sulaymaniyah", label: "Sulaymaniyah" },
          { value: "najaf", label: "Najaf" },
          { value: "karbala", label: "Karbala" },
        ],
      },
      {
        value: "jordan",
        label: "Jordan",
        states: [
          { value: "amman", label: "Amman" },
          { value: "zarqa", label: "Zarqa" },
          { value: "irbid", label: "Irbid" },
          { value: "aqaba", label: "Aqaba" },
          { value: "salt", label: "As-Salt" },
          { value: "madaba", label: "Madaba" },
        ],
      },
      {
        value: "kazakhstan",
        label: "Kazakhstan",
        states: [
          { value: "almaty", label: "Almaty" },
          { value: "astana", label: "Astana" },
          { value: "shymkent", label: "Shymkent" },
          { value: "karaganda", label: "Karaganda" },
          { value: "aktobe", label: "Aktobe" },
          { value: "atyrau", label: "Atyrau" },
          { value: "pavlodar", label: "Pavlodar" },
          { value: "kostanay", label: "Kostanay" },
          { value: "oral", label: "Oral" },
          { value: "semey", label: "Semey" },
        ],
      },
      {
        value: "kuwait",
        label: "Kuwait",
        states: [
          { value: "kuwait_city", label: "Kuwait City" },
          { value: "hawalli", label: "Hawalli" },
          { value: "farwaniya", label: "Farwaniya" },
          { value: "mubarak_al_kabeer", label: "Mubarak Al-Kabeer" },
          { value: "ahmadi", label: "Ahmadi" },
          { value: "jahra", label: "Jahra" },
        ],
      },
      {
        value: "kyrgyzstan",
        label: "Kyrgyzstan",
        states: [
          { value: "bishkek", label: "Bishkek" },
          { value: "osh", label: "Osh" },
          { value: "jalal_abad", label: "Jalal-Abad" },
          { value: "karakol", label: "Karakol" },
          { value: "naryn", label: "Naryn" },
          { value: "talas", label: "Talas" },
        ],
      },
      {
        value: "laos",
        label: "Laos",
        states: [
          { value: "vientiane", label: "Vientiane" },
          { value: "luang_prabang", label: "Luang Prabang" },
          { value: "savannakhet", label: "Savannakhet" },
          { value: "pakse", label: "Pakse" },
          { value: "xieng_khouang", label: "Xieng Khouang" },
        ],
      },
      {
        value: "lebanon",
        label: "Lebanon",
        states: [
          { value: "beirut", label: "Beirut" },
          { value: "tripoli_lb", label: "Tripoli" },
          { value: "sidon", label: "Sidon" },
          { value: "tyre", label: "Tyre" },
          { value: "zahle", label: "Zahlé" },
          { value: "jounieh", label: "Jounieh" },
          { value: "baabda", label: "Baabda" },
        ],
      },
      {
        value: "maldives",
        label: "Maldives",
        states: [
          { value: "male", label: "Malé" },
          { value: "addu_city", label: "Addu City" },
          { value: "hulhumale", label: "Hulhumalé" },
          { value: "fuvahmulah", label: "Fuvahmulah" },
          { value: "kulhudhuffushi", label: "Kulhudhuffushi" },
        ],
      },
      {
        value: "mongolia",
        label: "Mongolia",
        states: [
          { value: "ulaanbaatar", label: "Ulaanbaatar" },
          { value: "darkhan", label: "Darkhan" },
          { value: "erdenet", label: "Erdenet" },
          { value: "khovd", label: "Khovd" },
          { value: "ovorkhangai", label: "Övörkhangai" },
          { value: "selenge", label: "Selenge" },
        ],
      },
      {
        value: "myanmar",
        label: "Myanmar",
        states: [
          { value: "yangon", label: "Yangon" },
          { value: "mandalay", label: "Mandalay" },
          { value: "naypyidaw", label: "Naypyidaw" },
          { value: "bago", label: "Bago" },
          { value: "mawlamyine", label: "Mawlamyine" },
          { value: "taunggyi", label: "Taunggyi" },
          { value: "sittwe", label: "Sittwe" },
          { value: "pathein", label: "Pathein" },
        ],
      },
      {
        value: "nepal",
        label: "Nepal",
        states: [
          { value: "kathmandu", label: "Kathmandu" },
          { value: "pokhara", label: "Pokhara" },
          { value: "lalitpur", label: "Lalitpur" },
          { value: "biratnagar", label: "Biratnagar" },
          { value: "bharatpur", label: "Bharatpur" },
          { value: "birgunj", label: "Birgunj" },
          { value: "dharan", label: "Dharan" },
          { value: "bhaktapur", label: "Bhaktapur" },
        ],
      },
      {
        value: "oman",
        label: "Oman",
        states: [
          { value: "muscat", label: "Muscat" },
          { value: "salalah", label: "Salalah" },
          { value: "sohar", label: "Sohar" },
          { value: "nizwa", label: "Nizwa" },
          { value: "sur", label: "Sur" },
          { value: "ibra", label: "Ibra" },
        ],
      },
      {
        value: "pakistan",
        label: "Pakistan",
        states: [
          { value: "karachi", label: "Karachi" },
          { value: "lahore", label: "Lahore" },
          { value: "islamabad", label: "Islamabad" },
          { value: "faisalabad", label: "Faisalabad" },
          { value: "peshawar", label: "Peshawar" },
          { value: "quetta", label: "Quetta" },
          { value: "multan", label: "Multan" },
          { value: "sialkot", label: "Sialkot" },
          { value: "hyderabad_pk", label: "Hyderabad" },
          { value: "rawalpindi", label: "Rawalpindi" },
        ],
      },
      {
        value: "palestine",
        label: "Palestine",
        states: [
          { value: "gaza", label: "Gaza" },
          { value: "ramallah", label: "Ramallah" },
          { value: "hebron", label: "Hebron" },
          { value: "nablus", label: "Nablus" },
          { value: "bethlehem", label: "Bethlehem" },
          { value: "jenin", label: "Jenin" },
        ],
      },
      {
        value: "qatar",
        label: "Qatar",
        states: [
          { value: "doha", label: "Doha" },
          { value: "al_wakrah", label: "Al Wakrah" },
          { value: "al_khor", label: "Al Khor" },
          { value: "rayyan", label: "Al Rayyan" },
          { value: "umm_salal", label: "Umm Salal" },
        ],
      },
      {
        value: "sri_lanka",
        label: "Sri Lanka",
        states: [
          { value: "colombo", label: "Colombo" },
          { value: "kandy", label: "Kandy" },
          { value: "galle", label: "Galle" },
          { value: "jaffna", label: "Jaffna" },
          { value: "trincomalee", label: "Trincomalee" },
          { value: "batticaloa", label: "Batticaloa" },
          { value: "negombo", label: "Negombo" },
          { value: "anuradhapura", label: "Anuradhapura" },
        ],
      },
      {
        value: "syria",
        label: "Syria",
        states: [
          { value: "damascus", label: "Damascus" },
          { value: "aleppo", label: "Aleppo" },
          { value: "homs", label: "Homs" },
          { value: "latakia", label: "Latakia" },
          { value: "hama", label: "Hama" },
          { value: "deir_ez_zor", label: "Deir ez-Zor" },
          { value: "raqqa", label: "Raqqa" },
        ],
      },
      {
        value: "tajikistan",
        label: "Tajikistan",
        states: [
          { value: "dushanbe", label: "Dushanbe" },
          { value: "khujand", label: "Khujand" },
          { value: "khorugh", label: "Khorugh" },
          { value: "kulob", label: "Kulob" },
          { value: "istra", label: "Istaravshan" },
          { value: "penjikent", label: "Penjikent" },
        ],
      },
      {
        value: "timor_leste",
        label: "Timor-Leste",
        states: [
          { value: "dili", label: "Dili" },
          { value: "baucau", label: "Baucau" },
          { value: "suai", label: "Suai" },
          { value: "maliana", label: "Maliana" },
          { value: "_same", label: "Same" },
        ],
      },
      {
        value: "turkmenistan",
        label: "Turkmenistan",
        states: [
          { value: "ashgabat", label: "Ashgabat" },
          { value: "turkmenabat", label: "Türkmenabat" },
          { value: "dashoguz", label: "Daşoguz" },
          { value: "mary_tm", label: "Mary" },
          { value: "balkanabat", label: "Balkanabat" },
          { value: "turkmenbashi", label: "Türkmenbaşy" },
        ],
      },
      {
        value: "uzbekistan",
        label: "Uzbekistan",
        states: [
          { value: "tashkent", label: "Tashkent" },
          { value: "samarkand", label: "Samarkand" },
          { value: "bukhara", label: "Bukhara" },
          { value: "namangan", label: "Namangan" },
          { value: "andijan", label: "Andijan" },
          { value: "fergana", label: "Fergana" },
          { value: "nukus", label: "Nukus" },
          { value: "jizzakh", label: "Jizzakh" },
          { value: "navoiy", label: "Navoiy" },
        ],
      },
      {
        value: "vietnam",
        label: "Vietnam",
        states: [
          { value: "ho_chi_minh", label: "Ho Chi Minh City" },
          { value: "hanoi", label: "Hanoi" },
          { value: "da_nang", label: "Da Nang" },
          { value: "hai_phong", label: "Hai Phong" },
          { value: "can_tho", label: "Cần Thơ" },
          { value: "hue", label: "Huế" },
          { value: "nha_trang", label: "Nha Trang" },
          { value: "biên_hoa", label: "Biên Hòa" },
          { value: "quang_ninh", label: "Quảng Ninh" },
          { value: "binh_duong", label: "Bình Dương" },
        ],
      },
      {
        value: "yemen",
        label: "Yemen",
        states: [
          { value: "sanaa", label: "Sana'a" },
          { value: "aden", label: "Aden" },
          { value: "taiz", label: "Taiz" },
          { value: "hudaydah", label: "Al Hudaydah" },
          { value: "ibb", label: "Ibb" },
          { value: "mukalla", label: "Al Mukalla" },
          { value: "dhamar", label: "Dhamar" },
        ],
      },
    ],
  },
  {
    value: "oceania",
    label: "Oceania",
    emoji: "🌏",
    countries: [
      {
        value: "australia",
        label: "Australia",
        states: [
          { value: "new_south_wales", label: "New South Wales" },
          { value: "victoria", label: "Victoria" },
          { value: "queensland", label: "Queensland" },
          { value: "western_australia", label: "Western Australia" },
          { value: "south_australia", label: "South Australia" },
          { value: "tasmania", label: "Tasmania" },
          { value: "act", label: "Australian Capital Territory" },
          { value: "northern_territory", label: "Northern Territory" },
        ],
      },
      {
        value: "new_zealand",
        label: "New Zealand",
        states: [
          { value: "auckland", label: "Auckland" },
          { value: "wellington", label: "Wellington" },
          { value: "canterbury", label: "Canterbury" },
          { value: "otago", label: "Otago" },
          { value: "waikato", label: "Waikato" },
          { value: "bay_of_plenty", label: "Bay of Plenty" },
        ],
      },
      {
        value: "fiji",
        label: "Fiji",
        states: [
          { value: "suva", label: "Suva" },
          { value: "nadi", label: "Nadi" },
          { value: "lautoka", label: "Lautoka" },
          { value: "labasa", label: "Labasa" },
          { value: "ba", label: "Ba" },
        ],
      },
      {
        value: "kiribati",
        label: "Kiribati",
        states: [
          { value: "south_tarawa", label: "South Tarawa" },
          { value: "betio", label: "Betio" },
          { value: "bikenibeu", label: "Bikenibeu" },
          { value: "christmas_island", label: "Christmas Island" },
        ],
      },
      {
        value: "marshall_islands",
        label: "Marshall Islands",
        states: [
          { value: "majuro", label: "Majuro" },
          { value: "ebeye", label: "Ebeye" },
          { value: "arlak", label: "Arno" },
          { value: "jaluit", label: "Jaluit" },
        ],
      },
      {
        value: "micronesia",
        label: "Micronesia",
        states: [
          { value: "pohnpei", label: "Pohnpei" },
          { value: "chuuk", label: "Chuuk" },
          { value: "yap", label: "Yap" },
          { value: "kosrae", label: "Kosrae" },
          { value: "kolonia", label: "Kolonia" },
        ],
      },
      {
        value: "nauru",
        label: "Nauru",
        states: [
          { value: "yaren", label: "Yaren" },
          { value: "aiwo", label: "Aiwo" },
          { value: "denigomodu", label: "Denigomodu" },
          { value: "boe", label: "Boe" },
        ],
      },
      {
        value: "palau",
        label: "Palau",
        states: [
          { value: "koror", label: "Koror" },
          { value: "melekeok", label: "Melekeok" },
          { value: "airai", label: "Airai" },
          { value: "peleliu", label: "Peleliu" },
        ],
      },
      {
        value: "papua_new_guinea",
        label: "Papua New Guinea",
        states: [
          { value: "port_moresby", label: "Port Moresby" },
          { value: "lae", label: "Lae" },
          { value: "mt_hagen", label: "Mount Hagen" },
          { value: "goroka", label: "Goroka" },
          { value: "madang", label: "Madang" },
          { value: "wewak", label: "Wewak" },
          { value: "kokopo", label: "Kokopo" },
          { value: "alotau", label: "Alotau" },
        ],
      },
      {
        value: "samoa",
        label: "Samoa",
        states: [
          { value: "apia", label: "Apia" },
          { value: "vaitele", label: "Vaitele" },
          { value: "falefa", label: "Falefa" },
          { value: "leulumoega", label: "Leulumoega" },
          { value: "afega", label: "Afega" },
        ],
      },
      {
        value: "solomon_islands",
        label: "Solomon Islands",
        states: [
          { value: "honiara", label: "Honiara" },
          { value: "gizo", label: "Gizo" },
          { value: "auki", label: "Auki" },
          { value: "taro", label: "Taro" },
          { value: "kirakira", label: "Kira Kira" },
        ],
      },
      {
        value: "tonga",
        label: "Tonga",
        states: [
          { value: "nukualofa", label: "Nuku'alofa" },
          { value: "neiafu", label: "Neiafu" },
          { value: "vaini", label: "Vaini" },
          { value: "pangai", label: "Pangai" },
        ],
      },
      {
        value: "tuvalu",
        label: "Tuvalu",
        states: [
          { value: "funafuti", label: "Funafuti" },
          { value: "vaiaku", label: "Vaiaku" },
          { value: "nanumea", label: "Nanumea" },
          { value: "niutao", label: "Niutao" },
        ],
      },
      {
        value: "vanuatu",
        label: "Vanuatu",
        states: [
          { value: "port_vila", label: "Port Vila" },
          { value: "luganville", label: "Luganville" },
          { value: "isangel", label: "Isangel" },
          { value: "sola", label: "Sola" },
          { value: "saratamata", label: "Saratamata" },
        ],
      },
    ],
  },
];

export function getCountriesForContinent(continentValue: string): CountryData[] {
  const continent = locationData.find((c) => c.value === continentValue);
  return continent?.countries || [];
}

export function getStatesForCountry(continentValue: string, countryValue: string): LocationOption[] {
  const countries = getCountriesForContinent(continentValue);
  const country = countries.find((c) => c.value === countryValue);
  return country?.states || [];
}

export function getContinentLabel(value: string): string {
  const c = locationData.find((c) => c.value === value);
  return c ? `${c.emoji} ${c.label}` : "";
}

export function getCountryLabel(continentValue: string, countryValue: string): string {
  const countries = getCountriesForContinent(continentValue);
  const country = countries.find((c) => c.value === countryValue);
  return country?.label || "";
}
